# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - git submodule init
  - git submodule update
install:
  - pip install -U 'virtualenv==14.0.6'
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -V
  - python -c "import datetime;print('fold' in dir(datetime.datetime))"
  - pip install -r requirements-dev.txt
  - pip install codecov
  - pip install pytest-cov
  - pip install codecov
  - pip install coveralls
 
script:
  - paver test_all
  - paver coverage
  
after_success:
  - pwd
  - ls -la
  - coveralls --verbose
  - bash <(curl -s https://codecov.io/bash)
