# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

python:
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -U 'virtualenv==14.0.6'
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -V
  - pip install -r requirements-dev.txt

script:
  - paver test_all
