from zic.classes import *
from datetime import *


class Ghana(Rules):
    name ="Ghana"
    rules = [
        Rule(1920, 1943, None, Sep, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=20), letters='GHST'),
        Rule(1920, 1943, None, Dec, 31,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters='GMT'),
    ]

class Morocco(Rules):
    name ="Morocco"
    rules = [
        Rule(1939, 1940, None, Sep, 12,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1939, 1940, None, Nov, 19,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1940, 1941, None, Feb, 25,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1945, 1946, None, Nov, 18,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1950, 1951, None, Jun, 11,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1950, 1951, None, Oct, 29,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1967, 1968, None, Jun, 3,
             at=(timedelta(hours=12, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1967, 1968, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1974, 1975, None, Jun, 24,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1974, 1975, None, Sep, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1976, 1978, None, May, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1976, 1977, None, Aug, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1977, 1978, None, Sep, 28,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1978, 1979, None, Jun, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1978, 1979, None, Aug, 4,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2008, 2009, None, Jun, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2008, 2009, None, Sep, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2009, 2010, None, Jun, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2009, 2010, None, Aug, 21,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2010, 2011, None, May, 2,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2010, 2011, None, Aug, 8,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2011, 2012, None, Apr, 3,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2011, 2012, None, Jul, 31,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2012, 2014, None, Apr, lastSun,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2012, 2013, None, Jul, 20,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2012, 2013, None, Aug, 20,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2012, 2013, None, Sep, 30,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2013, 2014, None, Jul, 7,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2013, 2014, None, Aug, 10,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2013, 10000, None, Oct, lastSun,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2014, 2022, None, Mar, lastSun,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2014, 2015, None, Jun, 28,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2014, 2015, None, Aug, 2,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2015, 2016, None, Jun, 14,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2015, 2016, None, Jul, 19,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2016, 2017, None, Jun, 5,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2016, 2017, None, Jul, 10,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2017, 2018, None, May, 21,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2017, 2018, None, Jul, 2,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2018, 2019, None, May, 13,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2018, 2019, None, Jun, 17,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2019, 2020, None, May, 5,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2019, 2020, None, Jun, 9,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2020, 2021, None, Apr, 19,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2020, 2021, None, May, 24,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2021, 2022, None, Apr, 11,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2021, 2022, None, May, 16,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2022, 2023, None, May, 8,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2023, 2024, None, Apr, 23,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2024, 2025, None, Apr, 14,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2025, 2026, None, Apr, 6,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2026, 10000, None, Mar, lastSun,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2036, 2037, None, Oct, 19,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2037, 2038, None, Oct, 4,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Sudan(Rules):
    name ="Sudan"
    rules = [
        Rule(1970, 1971, None, May, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1970, 1986, None, Oct, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1971, 1972, None, Apr, 30,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1972, 1986, None, Apr, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
    ]

class Namibia(Rules):
    name ="Namibia"
    rules = [
        Rule(1994, 10000, None, Sep, Sun>=1,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1995, 10000, None, Apr, Sun>=1,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Egypt(Rules):
    name ="Egypt"
    rules = [
        Rule(1940, 1941, None, Jul, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1940, 1941, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1941, 1942, None, Apr, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1941, 1942, None, Sep, 16,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1942, 1945, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1942, 1943, None, Oct, 27,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1943, 1946, None, Nov, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1945, 1946, None, Apr, 16,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1957, 1958, None, May, 10,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1957, 1959, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1958, 1959, None, May, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1959, 1982, None, May, 1,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1959, 1966, None, Sep, 30,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1966, 1995, None, Oct, 1,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1982, 1983, None, Jul, 25,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1983, 1984, None, Jul, 12,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1984, 1989, None, May, 1,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1989, 1990, None, May, 6,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1990, 1995, None, May, 1,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1995, 2011, None, Apr, lastFri,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1995, 2006, None, Sep, lastThu,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2006, 2007, None, Sep, 21,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2007, 2008, None, Sep, Thu>=1,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2008, 2009, None, Aug, lastThu,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2009, 2010, None, Aug, 20,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2010, 2011, None, Aug, 10,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2010, 2011, None, Sep, 9,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2010, 2011, None, Sep, lastThu,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2014, 2015, None, May, 15,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2014, 2015, None, Jun, 26,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2014, 2015, None, Jul, 31,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2014, 2015, None, Sep, lastThu,
             at=(timedelta(1), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class SA(Rules):
    name ="SA"
    rules = [
        Rule(1942, 1944, None, Sep, Sun>=15,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters=''),
        Rule(1943, 1945, None, Mar, Sun>=15,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Tunisia(Rules):
    name ="Tunisia"
    rules = [
        Rule(1939, 1940, None, Apr, 15,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1939, 1940, None, Nov, 18,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1940, 1941, None, Feb, 25,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1941, 1942, None, Oct, 6,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1942, 1943, None, Mar, 9,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1942, 1943, None, Nov, 2,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1943, 1944, None, Mar, 29,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1943, 1944, None, Apr, 17,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1943, 1944, None, Apr, 25,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1943, 1944, None, Oct, 4,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1944, 1946, None, Apr, Mon>=1,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1944, 1945, None, Oct, 8,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1945, 1946, None, Sep, 16,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1977, 1978, None, Apr, 30,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1977, 1978, None, Sep, 24,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1978, 1979, None, May, 1,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1978, 1979, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1988, 1989, None, Jun, 1,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1988, 1991, None, Sep, lastSun,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1989, 1990, None, Mar, 26,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1990, 1991, None, May, 1,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2005, 2006, None, May, 1,
             at=(timedelta(hours=0, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2005, 2006, None, Sep, 30,
             at=(timedelta(hours=1, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(2006, 2009, None, Mar, lastSun,
             at=(timedelta(hours=2, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2006, 2009, None, Oct, lastSun,
             at=(timedelta(hours=2, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
    ]

class Algeria(Rules):
    name ="Algeria"
    rules = [
        Rule(1916, 1917, None, Jun, 14,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1916, 1920, None, Oct, Sun>=1,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1917, 1918, None, Mar, 24,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1918, 1919, None, Mar, 9,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1919, 1920, None, Mar, 1,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1920, 1921, None, Feb, 14,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1920, 1921, None, Oct, 23,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1921, 1922, None, Mar, 14,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1921, 1922, None, Jun, 21,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1939, 1940, None, Sep, 11,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1939, 1940, None, Nov, 19,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1944, 1946, None, Apr, Mon>=1,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1944, 1945, None, Oct, 8,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1945, 1946, None, Sep, 16,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1971, 1972, None, Apr, 25,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1971, 1972, None, Sep, 26,
             at=(timedelta(hours=23, minutes=0), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1977, 1978, None, May, 6,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1977, 1978, None, Oct, 21,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1978, 1979, None, Mar, 24,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1978, 1979, None, Sep, 22,
             at=(timedelta(hours=3, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1980, 1981, None, Apr, 25,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1980, 1981, None, Oct, 31,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Libya(Rules):
    name ="Libya"
    rules = [
        Rule(1951, 1952, None, Oct, 14,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1952, 1953, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1953, 1954, None, Oct, 9,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1954, 1955, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1955, 1956, None, Sep, 30,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1956, 1957, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1982, 1985, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1982, 1986, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1985, 1986, None, Apr, 6,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1986, 1987, None, Apr, 4,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1986, 1987, None, Oct, 3,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1987, 1990, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1987, 1990, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1997, 1998, None, Apr, 4,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1997, 1998, None, Oct, 4,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2013, 2014, None, Mar, lastFri,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2013, 2014, None, Oct, lastFri,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Mauritius(Rules):
    name ="Mauritius"
    rules = [
        Rule(1982, 1983, None, Oct, 10,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1983, 1984, None, Mar, 21,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2008, 2009, None, Oct, lastSun,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2009, 2010, None, Mar, lastSun,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Africa:
    class Abidjan(Zone):
        name = 'Abidjan'
        observances = [
            Observance(gmtoff=(0, -16, -8),
                       rules=None,
                       format='LMT',
                       until=1912),
            Observance(gmtoff=0,
                       rules=None,
                       format='GMT',
                       until=None),
        ]

    class Accra(Zone):
        name = 'Accra'
        observances = [
            Observance(gmtoff=(0, 0, -52),
                       rules=None,
                       format='LMT',
                       until=1918),
            Observance(gmtoff=0,
                       rules=Ghana,
                       format='%s',
                       until=None),
        ]

    class Algiers(Zone):
        name = 'Algiers'
        observances = [
            Observance(gmtoff=(0, 12, 12),
                       rules=None,
                       format='LMT',
                       until=(1891, Mar, 15, 0, 1, wall)),
            Observance(gmtoff=(0, 9, 21),
                       rules=None,
                       format='PMT',
                       until=(1911, Mar, 11)),
            Observance(gmtoff=0,
                       rules=Algeria,
                       format='WE%sT',
                       until=(1940, Feb, 25, 2, 0, wall)),
            Observance(gmtoff=1,
                       rules=Algeria,
                       format='CE%sT',
                       until=(1946, Oct, 7)),
            Observance(gmtoff=0,
                       rules=None,
                       format='WET',
                       until=(1956, Jan, 29)),
            Observance(gmtoff=1,
                       rules=None,
                       format='CET',
                       until=(1963, Apr, 14)),
            Observance(gmtoff=0,
                       rules=Algeria,
                       format='WE%sT',
                       until=(1977, Oct, 21)),
            Observance(gmtoff=1,
                       rules=Algeria,
                       format='CE%sT',
                       until=(1979, Oct, 26)),
            Observance(gmtoff=0,
                       rules=Algeria,
                       format='WE%sT',
                       until=(1981, May)),
            Observance(gmtoff=1,
                       rules=None,
                       format='CET',
                       until=None),
        ]

    class Bissau(Zone):
        name = 'Bissau'
        observances = [
            Observance(gmtoff=(-1, -2, -20),
                       rules=None,
                       format='LMT',
                       until=(1912, Jan, 1)),
            Observance(gmtoff=-1,
                       rules=None,
                       format='WAT',
                       until=1975),
            Observance(gmtoff=0,
                       rules=None,
                       format='GMT',
                       until=None),
        ]

    class Cairo(Zone):
        name = 'Cairo'
        observances = [
            Observance(gmtoff=(2, 5, 9),
                       rules=None,
                       format='LMT',
                       until=(1900, Oct)),
            Observance(gmtoff=2,
                       rules=Egypt,
                       format='EE%sT',
                       until=None),
        ]

    class Casablanca(Zone):
        name = 'Casablanca'
        observances = [
            Observance(gmtoff=(0, -30, -20),
                       rules=None,
                       format='LMT',
                       until=(1913, Oct, 26)),
            Observance(gmtoff=0,
                       rules=Morocco,
                       format='WE%sT',
                       until=(1984, Mar, 16)),
            Observance(gmtoff=1,
                       rules=None,
                       format='CET',
                       until=1986),
            Observance(gmtoff=0,
                       rules=Morocco,
                       format='WE%sT',
                       until=None),
        ]

    class El_Aaiun(Zone):
        name = 'El_Aaiun'
        observances = [
            Observance(gmtoff=(0, -52, -48),
                       rules=None,
                       format='LMT',
                       until=(1934, Jan)),
            Observance(gmtoff=-1,
                       rules=None,
                       format='WAT',
                       until=(1976, Apr, 14)),
            Observance(gmtoff=0,
                       rules=Morocco,
                       format='WE%sT',
                       until=None),
        ]

    class Johannesburg(Zone):
        name = 'Johannesburg'
        observances = [
            Observance(gmtoff=(1, 52),
                       rules=None,
                       format='LMT',
                       until=(1892, Feb, 8)),
            Observance(gmtoff=(1, 30),
                       rules=None,
                       format='SAST',
                       until=(1903, Mar)),
            Observance(gmtoff=2,
                       rules=SA,
                       format='SAST',
                       until=None),
        ]

    class Khartoum(Zone):
        name = 'Khartoum'
        observances = [
            Observance(gmtoff=(2, 10, 8),
                       rules=None,
                       format='LMT',
                       until=1931),
            Observance(gmtoff=2,
                       rules=Sudan,
                       format='CA%sT',
                       until=(2000, Jan, 15, 12, 0, wall)),
            Observance(gmtoff=3,
                       rules=None,
                       format='EAT',
                       until=None),
        ]

    class Lagos(Zone):
        name = 'Lagos'
        observances = [
            Observance(gmtoff=(0, 13, 36),
                       rules=None,
                       format='LMT',
                       until=(1919, Sep)),
            Observance(gmtoff=1,
                       rules=None,
                       format='WAT',
                       until=None),
        ]

    class Maputo(Zone):
        name = 'Maputo'
        observances = [
            Observance(gmtoff=(2, 10, 20),
                       rules=None,
                       format='LMT',
                       until=(1903, Mar)),
            Observance(gmtoff=2,
                       rules=None,
                       format='CAT',
                       until=None),
        ]

    class Monrovia(Zone):
        name = 'Monrovia'
        observances = [
            Observance(gmtoff=(0, -43, -8),
                       rules=None,
                       format='LMT',
                       until=1882),
            Observance(gmtoff=(0, -43, -8),
                       rules=None,
                       format='MMT',
                       until=(1919, Mar)),
            Observance(gmtoff=(0, -44, -30),
                       rules=None,
                       format='LRT',
                       until=(1972, May)),
            Observance(gmtoff=0,
                       rules=None,
                       format='GMT',
                       until=None),
        ]

    class Nairobi(Zone):
        name = 'Nairobi'
        observances = [
            Observance(gmtoff=(2, 27, 16),
                       rules=None,
                       format='LMT',
                       until=(1928, Jul)),
            Observance(gmtoff=3,
                       rules=None,
                       format='EAT',
                       until=1930),
            Observance(gmtoff=(2, 30),
                       rules=None,
                       format='BEAT',
                       until=1940),
            Observance(gmtoff=(2, 45),
                       rules=None,
                       format='BEAUT',
                       until=1960),
            Observance(gmtoff=3,
                       rules=None,
                       format='EAT',
                       until=None),
        ]

    class Ndjamena(Zone):
        name = 'Ndjamena'
        observances = [
            Observance(gmtoff=(1, 0, 12),
                       rules=None,
                       format='LMT',
                       until=1912),
            Observance(gmtoff=1,
                       rules=None,
                       format='WAT',
                       until=(1979, Oct, 14)),
            Observance(gmtoff=1,
                       rules='1:00',
                       format='WAST',
                       until=(1980, Mar, 8)),
            Observance(gmtoff=1,
                       rules=None,
                       format='WAT',
                       until=None),
        ]

    class Tripoli(Zone):
        name = 'Tripoli'
        observances = [
            Observance(gmtoff=(0, 52, 44),
                       rules=None,
                       format='LMT',
                       until=1920),
            Observance(gmtoff=1,
                       rules=Libya,
                       format='CE%sT',
                       until=1959),
            Observance(gmtoff=2,
                       rules=None,
                       format='EET',
                       until=1982),
            Observance(gmtoff=1,
                       rules=Libya,
                       format='CE%sT',
                       until=(1990, May, 4)),
            Observance(gmtoff=2,
                       rules=None,
                       format='EET',
                       until=(1996, Sep, 30)),
            Observance(gmtoff=1,
                       rules=Libya,
                       format='CE%sT',
                       until=(1997, Oct, 4)),
            Observance(gmtoff=2,
                       rules=None,
                       format='EET',
                       until=(2012, Nov, 10, 2, 0, wall)),
            Observance(gmtoff=1,
                       rules=Libya,
                       format='CE%sT',
                       until=(2013, Oct, 25, 2, 0, wall)),
            Observance(gmtoff=2,
                       rules=None,
                       format='EET',
                       until=None),
        ]

    class Tunis(Zone):
        name = 'Tunis'
        observances = [
            Observance(gmtoff=(0, 40, 44),
                       rules=None,
                       format='LMT',
                       until=(1881, May, 12)),
            Observance(gmtoff=(0, 9, 21),
                       rules=None,
                       format='PMT',
                       until=(1911, Mar, 11)),
            Observance(gmtoff=1,
                       rules=Tunisia,
                       format='CE%sT',
                       until=None),
        ]

    class Windhoek(Zone):
        name = 'Windhoek'
        observances = [
            Observance(gmtoff=(1, 8, 24),
                       rules=None,
                       format='LMT',
                       until=(1892, Feb, 8)),
            Observance(gmtoff=(1, 30),
                       rules=None,
                       format='SWAT',
                       until=(1903, Mar)),
            Observance(gmtoff=2,
                       rules=None,
                       format='SAST',
                       until=(1942, Sep, 20, 2, 0, wall)),
            Observance(gmtoff=2,
                       rules='1:00',
                       format='SAST',
                       until=(1943, Mar, 21, 2, 0, wall)),
            Observance(gmtoff=2,
                       rules=None,
                       format='SAST',
                       until=(1990, Mar, 21)),
            Observance(gmtoff=2,
                       rules=None,
                       format='CAT',
                       until=(1994, Apr, 3)),
            Observance(gmtoff=1,
                       rules=Namibia,
                       format='WA%sT',
                       until=None),
        ]

class Atlantic:
    class Cape_Verde(Zone):
        name = 'Cape_Verde'
        observances = [
            Observance(gmtoff=(-1, -34, -4),
                       rules=None,
                       format='LMT',
                       until=1907),
            Observance(gmtoff=-2,
                       rules=None,
                       format='CVT',
                       until=(1942, Sep)),
            Observance(gmtoff=-2,
                       rules='1:00',
                       format='CVST',
                       until=(1945, Oct, 15)),
            Observance(gmtoff=-2,
                       rules=None,
                       format='CVT',
                       until=(1975, Nov, 25, 2, 0, wall)),
            Observance(gmtoff=-1,
                       rules=None,
                       format='CVT',
                       until=None),
        ]

class Indian:
    class Mahe(Zone):
        name = 'Mahe'
        observances = [
            Observance(gmtoff=(3, 41, 48),
                       rules=None,
                       format='LMT',
                       until=(1906, Jun)),
            Observance(gmtoff=4,
                       rules=None,
                       format='SCT',
                       until=None),
        ]

    class Mauritius(Zone):
        name = 'Mauritius'
        observances = [
            Observance(gmtoff=(3, 50),
                       rules=None,
                       format='LMT',
                       until=1907),
            Observance(gmtoff=4,
                       rules=Mauritius,
                       format='MU%sT',
                       until=None),
        ]

    class Reunion(Zone):
        name = 'Reunion'
        observances = [
            Observance(gmtoff=(3, 41, 52),
                       rules=None,
                       format='LMT',
                       until=(1911, Jun)),
            Observance(gmtoff=4,
                       rules=None,
                       format='RET',
                       until=None),
        ]

