from zic.classes import *
from datetime import *


class Brazil(Rules):
    name ="Brazil"
    rules = [
        Rule(1931, 1932, None, Oct, 3,
             at=(timedelta(hours=11, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1932, 1934, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1932, 1933, None, Oct, 3,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1949, 1953, None, Dec, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1950, 1951, None, Apr, 16,
             at=(timedelta(hours=1, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1951, 1953, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1953, 1954, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1963, 1964, None, Dec, 9,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1964, 1965, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1965, 1966, None, Jan, 31,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1965, 1966, None, Mar, 31,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1965, 1966, None, Dec, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1966, 1969, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1966, 1968, None, Nov, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1985, 1986, None, Nov, 2,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1986, 1987, None, Mar, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1986, 1987, None, Oct, 25,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1987, 1988, None, Feb, 14,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1987, 1988, None, Oct, 25,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1988, 1989, None, Feb, 7,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1988, 1989, None, Oct, 16,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1989, 1990, None, Jan, 29,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1989, 1990, None, Oct, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1990, 1991, None, Feb, 11,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1990, 1991, None, Oct, 21,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1991, 1992, None, Feb, 17,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1991, 1992, None, Oct, 20,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1992, 1993, None, Feb, 9,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1992, 1993, None, Oct, 25,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1993, 1994, None, Jan, 31,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1993, 1996, None, Oct, Sun>=11,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1994, 1996, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1996, 1997, None, Feb, 11,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1996, 1997, None, Oct, 6,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1997, 1998, None, Feb, 16,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1997, 1998, None, Oct, 6,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1998, 1999, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1998, 1999, None, Oct, 11,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1999, 2000, None, Feb, 21,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1999, 2000, None, Oct, 3,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2000, 2001, None, Feb, 27,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2000, 2002, None, Oct, Sun>=8,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2001, 2007, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2002, 2003, None, Nov, 3,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2003, 2004, None, Oct, 19,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2004, 2005, None, Nov, 2,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2005, 2006, None, Oct, 16,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2006, 2007, None, Nov, 5,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2007, 2008, None, Feb, 25,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2007, 2008, None, Oct, Sun>=8,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2008, 10000, None, Oct, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2008, 2012, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2012, 2013, None, Feb, Sun>=22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2013, 2015, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2015, 2016, None, Feb, Sun>=22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2016, 2023, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2023, 2024, None, Feb, Sun>=22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2024, 2026, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2026, 2027, None, Feb, Sun>=22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2027, 2034, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2034, 2035, None, Feb, Sun>=22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2035, 2037, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2037, 2038, None, Feb, Sun>=22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2038, 10000, None, Feb, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Peru(Rules):
    name ="Peru"
    rules = [
        Rule(1938, 1939, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1938, 1939, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1938, 1940, None, Sep, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1939, 1941, None, Mar, Sun>=24,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1986, 1988, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1986, 1988, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1990, 1991, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1990, 1991, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1994, 1995, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1994, 1995, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Para(Rules):
    name ="Para"
    rules = [
        Rule(1975, 1989, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1975, 1979, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1979, 1992, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1989, 1990, None, Oct, 22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1990, 1991, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1991, 1992, None, Oct, 6,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1992, 1993, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1992, 1993, None, Oct, 5,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1993, 1994, None, Mar, 31,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1993, 1996, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1994, 1996, None, Feb, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1996, 1997, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1996, 2002, None, Oct, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1997, 1998, None, Feb, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1998, 2002, None, Mar, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2002, 2005, None, Apr, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2002, 2004, None, Sep, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2004, 2010, None, Oct, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2005, 2010, None, Mar, Sun>=8,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2010, 10000, None, Oct, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2010, 2013, None, Apr, Sun>=8,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2013, 10000, None, Mar, Sun>=22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Uruguay(Rules):
    name ="Uruguay"
    rules = [
        Rule(1923, 1924, None, Oct, 2,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=30), letters='HS'),
        Rule(1924, 1927, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1924, 1926, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=30), letters='HS'),
        Rule(1933, 1936, None, Oct, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=30), letters='HS'),
        Rule(1934, 1937, None, Mar, Sat>=25,
             at=(timedelta(hours=23, minutes=30), 'std'),
             save=timedelta(hours=0), letters=''),
        Rule(1936, 1937, None, Nov, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=30), letters='HS'),
        Rule(1937, 1942, None, Mar, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1937, 1941, None, Oct, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=30), letters='HS'),
        Rule(1941, 1942, None, Aug, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=30), letters='HS'),
        Rule(1942, 1943, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1942, 1943, None, Dec, 14,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1943, 1944, None, Mar, 14,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1959, 1960, None, May, 24,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1959, 1960, None, Nov, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1960, 1961, None, Jan, 17,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1960, 1961, None, Mar, 6,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1965, 1968, None, Apr, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1965, 1966, None, Sep, 26,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1966, 1968, None, Oct, 31,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1968, 1971, None, May, 27,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=30), letters='HS'),
        Rule(1968, 1971, None, Dec, 2,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1972, 1973, None, Apr, 24,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1972, 1973, None, Aug, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1974, 1975, None, Mar, 10,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0, minutes=30), letters='HS'),
        Rule(1974, 1975, None, Dec, 22,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1976, 1977, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1977, 1978, None, Dec, 4,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1978, 1979, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1979, 1980, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1980, 1981, None, May, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1987, 1988, None, Dec, 14,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1988, 1989, None, Mar, 14,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1988, 1989, None, Dec, 11,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1989, 1990, None, Mar, 12,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1989, 1990, None, Oct, 29,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1990, 1993, None, Mar, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1990, 1992, None, Oct, Sun>=21,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1992, 1993, None, Oct, 18,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1993, 1994, None, Feb, 28,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2004, 2005, None, Sep, 19,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2005, 2006, None, Mar, 27,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2005, 2006, None, Oct, 9,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2006, 2007, None, Mar, 12,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2006, 2015, None, Oct, Sun>=1,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2007, 2016, None, Mar, Sun>=8,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Chile(Rules):
    name ="Chile"
    rules = [
        Rule(1927, 1932, None, Sep, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1928, 1933, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1968, 1969, None, Nov, 3,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1969, 1970, None, Mar, 30,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1969, 1970, None, Nov, 23,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1970, 1971, None, Mar, 29,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1971, 1972, None, Mar, 14,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1970, 1973, None, Oct, Sun>=9,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1972, 1987, None, Mar, Sun>=9,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1973, 1974, None, Sep, 30,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1974, 1988, None, Oct, Sun>=9,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1987, 1988, None, Apr, 12,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1988, 1991, None, Mar, Sun>=9,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1988, 1990, None, Oct, Sun>=9,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1990, 1991, None, Sep, 16,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1991, 1997, None, Mar, Sun>=9,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1991, 1998, None, Oct, Sun>=9,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1997, 1998, None, Mar, 30,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1998, 1999, None, Mar, Sun>=9,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1998, 1999, None, Sep, 27,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1999, 2000, None, Apr, 4,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(1999, 2011, None, Oct, Sun>=9,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2000, 2008, None, Mar, Sun>=9,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(2008, 2009, None, Mar, 30,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(2009, 2010, None, Mar, Sun>=9,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(2010, 2011, None, Apr, Sun>=1,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(2011, 2012, None, May, Sun>=2,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(2011, 2012, None, Aug, Sun>=16,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2012, 2015, None, Apr, Sun>=23,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(2012, 2015, None, Sep, Sun>=2,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2016, 10000, None, May, Sun>=9,
             at=(timedelta(hours=3, minutes=0), 'utc'),
             save=timedelta(hours=0), letters=''),
        Rule(2016, 10000, None, Aug, Sun>=9,
             at=(timedelta(hours=4, minutes=0), 'utc'),
             save=timedelta(hours=1, minutes=0), letters='S'),
    ]

class Falk(Rules):
    name ="Falk"
    rules = [
        Rule(1937, 1939, None, Sep, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1938, 1943, None, Mar, Sun>=19,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1939, 1940, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1940, 1943, None, Sep, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1943, 1944, None, Jan, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1983, 1984, None, Sep, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1984, 1986, None, Apr, lastSun,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1984, 1985, None, Sep, 16,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1985, 2001, None, Sep, Sun>=9,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1986, 2001, None, Apr, Sun>=16,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2001, 2011, None, Apr, Sun>=15,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2001, 2011, None, Sep, Sun>=1,
             at=(timedelta(hours=2, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
    ]

class CO(Rules):
    name ="CO"
    rules = [
        Rule(1992, 1993, None, May, 3,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1993, 1994, None, Apr, 4,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
    ]

class Arg(Rules):
    name ="Arg"
    rules = [
        Rule(1930, 1931, None, Dec, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1931, 1932, None, Apr, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1931, 1932, None, Oct, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1932, 1941, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1932, 1940, None, Nov, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1940, 1941, None, Jul, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1941, 1942, None, Jun, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1941, 1942, None, Oct, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1943, 1944, None, Aug, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1943, 1944, None, Oct, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1946, 1947, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1946, 1947, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1963, 1964, None, Oct, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1963, 1964, None, Dec, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1964, 1967, None, Mar, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1964, 1967, None, Oct, 15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1967, 1968, None, Apr, 2,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1967, 1969, None, Oct, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1968, 1970, None, Apr, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1974, 1975, None, Jan, 23,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1974, 1975, None, May, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1988, 1989, None, Dec, 1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1989, 1994, None, Mar, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(1989, 1993, None, Oct, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(1999, 2000, None, Oct, Sun>=1,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2000, 2001, None, Mar, 3,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2007, 2008, None, Dec, 30,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
        Rule(2008, 2010, None, Mar, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2008, 2009, None, Oct, Sun>=15,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
    ]

class SanLuis(Rules):
    name ="SanLuis"
    rules = [
        Rule(2008, 2010, None, Mar, Sun>=8,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=0), letters=''),
        Rule(2007, 2009, None, Oct, Sun>=8,
             at=(timedelta(hours=0, minutes=0), 'wall'),
             save=timedelta(hours=1, minutes=0), letters='S'),
    ]

class America:
    class Araguaina(Zone):
        name = 'Araguaina'
        observances = [
            Observance(gmtoff=(-3, -12, -48),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(1990, Sep, 17)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(1995, Sep, 14)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2003, Sep, 24)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(2012, Oct, 21)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2013, Sep)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=None),
        ]

    class Argentina:
        class Buenos_Aires(Zone):
            name = 'Buenos_Aires'
            observances = [
                Observance(gmtoff=(-3, -53, -48),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=None),
            ]

        class Catamarca(Zone):
            name = 'Catamarca'
            observances = [
                Observance(gmtoff=(-4, -23, -8),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1991, Mar, 3)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, Oct, 20)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(2004, Jun, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(2004, Jun, 20)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

        class Cordoba(Zone):
            name = 'Cordoba'
            observances = [
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1991, Mar, 3)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, Oct, 20)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=None),
            ]

        class Jujuy(Zone):
            name = 'Jujuy'
            observances = [
                Observance(gmtoff=(-4, -21, -12),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1990, Mar, 4)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1990, Oct, 28)),
                Observance(gmtoff=-4,
                           rules='1:00',
                           format='WARST',
                           until=(1991, Mar, 17)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, Oct, 6)),
                Observance(gmtoff=-3,
                           rules='1:00',
                           format='ARST',
                           until=1992),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

        class La_Rioja(Zone):
            name = 'La_Rioja'
            observances = [
                Observance(gmtoff=(-4, -27, -24),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1991, Mar, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, May, 7)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(2004, Jun, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(2004, Jun, 20)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

        class Mendoza(Zone):
            name = 'Mendoza'
            observances = [
                Observance(gmtoff=(-4, -35, -16),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1990, Mar, 4)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1990, Oct, 15)),
                Observance(gmtoff=-4,
                           rules='1:00',
                           format='WARST',
                           until=(1991, Mar, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, Oct, 15)),
                Observance(gmtoff=-4,
                           rules='1:00',
                           format='WARST',
                           until=(1992, Mar, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1992, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(2004, May, 23)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(2004, Sep, 26)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

        class Rio_Gallegos(Zone):
            name = 'Rio_Gallegos'
            observances = [
                Observance(gmtoff=(-4, -36, -52),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(2004, Jun, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(2004, Jun, 20)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

        class Salta(Zone):
            name = 'Salta'
            observances = [
                Observance(gmtoff=(-4, -21, -40),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1991, Mar, 3)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, Oct, 20)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

        class San_Juan(Zone):
            name = 'San_Juan'
            observances = [
                Observance(gmtoff=(-4, -34, -4),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1991, Mar, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, May, 7)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(2004, May, 31)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(2004, Jul, 25)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

        class San_Luis(Zone):
            name = 'San_Luis'
            observances = [
                Observance(gmtoff=(-4, -25, -24),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=1990),
                Observance(gmtoff=-3,
                           rules='1:00',
                           format='ARST',
                           until=(1990, Mar, 14)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1990, Oct, 15)),
                Observance(gmtoff=-4,
                           rules='1:00',
                           format='WARST',
                           until=(1991, Mar, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, Jun, 1)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules='1:00',
                           format='WARST',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(2004, May, 31)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(2004, Jul, 25)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Jan, 21)),
                Observance(gmtoff=-4,
                           rules=SanLuis,
                           format='WAR%sT',
                           until=(2009, Oct, 11)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

        class Tucuman(Zone):
            name = 'Tucuman'
            observances = [
                Observance(gmtoff=(-4, -20, -52),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1991, Mar, 3)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(1991, Oct, 20)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(2004, Jun, 1)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(2004, Jun, 13)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=None),
            ]

        class Ushuaia(Zone):
            name = 'Ushuaia'
            observances = [
                Observance(gmtoff=(-4, -33, -12),
                           rules=None,
                           format='LMT',
                           until=(1894, Oct, 31)),
                Observance(gmtoff=(-4, -16, -48),
                           rules=None,
                           format='CMT',
                           until=(1920, May)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='ART',
                           until=(1930, Dec)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(1969, Oct, 5)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(1999, Oct, 3)),
                Observance(gmtoff=-4,
                           rules=Arg,
                           format='AR%sT',
                           until=(2000, Mar, 3)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=(2004, May, 30)),
                Observance(gmtoff=-4,
                           rules=None,
                           format='WART',
                           until=(2004, Jun, 20)),
                Observance(gmtoff=-3,
                           rules=Arg,
                           format='AR%sT',
                           until=(2008, Oct, 18)),
                Observance(gmtoff=-3,
                           rules=None,
                           format='ART',
                           until=None),
            ]

    class Asuncion(Zone):
        name = 'Asuncion'
        observances = [
            Observance(gmtoff=(-3, -50, -40),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=(-3, -50, -40),
                       rules=None,
                       format='AMT',
                       until=(1931, Oct, 10)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='PYT',
                       until=(1972, Oct)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='PYT',
                       until=(1974, Apr)),
            Observance(gmtoff=-4,
                       rules=Para,
                       format='PY%sT',
                       until=None),
        ]

    class Bahia(Zone):
        name = 'Bahia'
        observances = [
            Observance(gmtoff=(-2, -34, -4),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2003, Sep, 24)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(2011, Oct, 16)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2012, Oct, 21)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=None),
        ]

    class Belem(Zone):
        name = 'Belem'
        observances = [
            Observance(gmtoff=(-3, -13, -56),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(1988, Sep, 12)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=None),
        ]

    class Boa_Vista(Zone):
        name = 'Boa_Vista'
        observances = [
            Observance(gmtoff=(-4, -2, -40),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=(1988, Sep, 12)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=(1999, Sep, 30)),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=(2000, Oct, 15)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=None),
        ]

    class Bogota(Zone):
        name = 'Bogota'
        observances = [
            Observance(gmtoff=(-4, -56, -16),
                       rules=None,
                       format='LMT',
                       until=(1884, Mar, 13)),
            Observance(gmtoff=(-4, -56, -16),
                       rules=None,
                       format='BMT',
                       until=(1914, Nov, 23)),
            Observance(gmtoff=-5,
                       rules=CO,
                       format='CO%sT',
                       until=None),
        ]

    class Campo_Grande(Zone):
        name = 'Campo_Grande'
        observances = [
            Observance(gmtoff=(-3, -38, -28),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=None),
        ]

    class Caracas(Zone):
        name = 'Caracas'
        observances = [
            Observance(gmtoff=(-4, -27, -44),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=(-4, -27, -40),
                       rules=None,
                       format='CMT',
                       until=(1912, Feb, 12)),
            Observance(gmtoff=(-4, -30),
                       rules=None,
                       format='VET',
                       until=(1965, Jan, 1, 0, 0, wall)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='VET',
                       until=(2007, Dec, 9, 3, 0, wall)),
            Observance(gmtoff=(-4, -30),
                       rules=None,
                       format='VET',
                       until=(2016, May, 1, 2, 30, wall)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='VET',
                       until=None),
        ]

    class Cayenne(Zone):
        name = 'Cayenne'
        observances = [
            Observance(gmtoff=(-3, -29, -20),
                       rules=None,
                       format='LMT',
                       until=(1911, Jul)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='GFT',
                       until=(1967, Oct)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='GFT',
                       until=None),
        ]

    class Cuiaba(Zone):
        name = 'Cuiaba'
        observances = [
            Observance(gmtoff=(-3, -44, -20),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=(2003, Sep, 24)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=(2004, Oct, 1)),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=None),
        ]

    class Curacao(Zone):
        name = 'Curacao'
        observances = [
            Observance(gmtoff=(-4, -35, -47),
                       rules=None,
                       format='LMT',
                       until=(1912, Feb, 12)),
            Observance(gmtoff=(-4, -30),
                       rules=None,
                       format='ANT',
                       until=1965),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AST',
                       until=None),
        ]

    class Eirunepe(Zone):
        name = 'Eirunepe'
        observances = [
            Observance(gmtoff=(-4, -39, -28),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-5,
                       rules=Brazil,
                       format='AC%sT',
                       until=(1988, Sep, 12)),
            Observance(gmtoff=-5,
                       rules=None,
                       format='ACT',
                       until=(1993, Sep, 28)),
            Observance(gmtoff=-5,
                       rules=Brazil,
                       format='AC%sT',
                       until=(1994, Sep, 22)),
            Observance(gmtoff=-5,
                       rules=None,
                       format='ACT',
                       until=(2008, Jun, 24, 0, 0, wall)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=(2013, Nov, 10)),
            Observance(gmtoff=-5,
                       rules=None,
                       format='ACT',
                       until=None),
        ]

    class Fortaleza(Zone):
        name = 'Fortaleza'
        observances = [
            Observance(gmtoff=(-2, -34),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(1990, Sep, 17)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(1999, Sep, 30)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2000, Oct, 22)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(2001, Sep, 13)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2002, Oct, 1)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=None),
        ]

    class Guayaquil(Zone):
        name = 'Guayaquil'
        observances = [
            Observance(gmtoff=(-5, -19, -20),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=(-5, -14),
                       rules=None,
                       format='QMT',
                       until=1931),
            Observance(gmtoff=-5,
                       rules=None,
                       format='ECT',
                       until=None),
        ]

    class Guyana(Zone):
        name = 'Guyana'
        observances = [
            Observance(gmtoff=(-3, -52, -40),
                       rules=None,
                       format='LMT',
                       until=(1915, Mar)),
            Observance(gmtoff=(-3, -45),
                       rules=None,
                       format='GBGT',
                       until=(1966, May, 26)),
            Observance(gmtoff=(-3, -45),
                       rules=None,
                       format='GYT',
                       until=(1975, Jul, 31)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='GYT',
                       until=1991),
            Observance(gmtoff=-4,
                       rules=None,
                       format='GYT',
                       until=None),
        ]

    class La_Paz(Zone):
        name = 'La_Paz'
        observances = [
            Observance(gmtoff=(-4, -32, -36),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=(-4, -32, -36),
                       rules=None,
                       format='CMT',
                       until=(1931, Oct, 15)),
            Observance(gmtoff=(-4, -32, -36),
                       rules='1:00',
                       format='BOST',
                       until=(1932, Mar, 21)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='BOT',
                       until=None),
        ]

    class Lima(Zone):
        name = 'Lima'
        observances = [
            Observance(gmtoff=(-5, -8, -12),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=(-5, -8, -36),
                       rules=None,
                       format='LMT',
                       until=(1908, Jul, 28)),
            Observance(gmtoff=-5,
                       rules=Peru,
                       format='PE%sT',
                       until=None),
        ]

    class Maceio(Zone):
        name = 'Maceio'
        observances = [
            Observance(gmtoff=(-2, -22, -52),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(1990, Sep, 17)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(1995, Oct, 13)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(1996, Sep, 4)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(1999, Sep, 30)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2000, Oct, 22)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(2001, Sep, 13)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2002, Oct, 1)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=None),
        ]

    class Manaus(Zone):
        name = 'Manaus'
        observances = [
            Observance(gmtoff=(-4, 0, -4),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=(1988, Sep, 12)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=(1993, Sep, 28)),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=(1994, Sep, 22)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=None),
        ]

    class Montevideo(Zone):
        name = 'Montevideo'
        observances = [
            Observance(gmtoff=(-3, -44, -44),
                       rules=None,
                       format='LMT',
                       until=(1898, Jun, 28)),
            Observance(gmtoff=(-3, -44, -44),
                       rules=None,
                       format='MMT',
                       until=(1920, May, 1)),
            Observance(gmtoff=(-3, -30),
                       rules=Uruguay,
                       format='UY%sT',
                       until=(1942, Dec, 14)),
            Observance(gmtoff=-3,
                       rules=Uruguay,
                       format='UY%sT',
                       until=None),
        ]

    class Noronha(Zone):
        name = 'Noronha'
        observances = [
            Observance(gmtoff=(-2, -9, -40),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-2,
                       rules=Brazil,
                       format='FN%sT',
                       until=(1990, Sep, 17)),
            Observance(gmtoff=-2,
                       rules=None,
                       format='FNT',
                       until=(1999, Sep, 30)),
            Observance(gmtoff=-2,
                       rules=Brazil,
                       format='FN%sT',
                       until=(2000, Oct, 15)),
            Observance(gmtoff=-2,
                       rules=None,
                       format='FNT',
                       until=(2001, Sep, 13)),
            Observance(gmtoff=-2,
                       rules=Brazil,
                       format='FN%sT',
                       until=(2002, Oct, 1)),
            Observance(gmtoff=-2,
                       rules=None,
                       format='FNT',
                       until=None),
        ]

    class Paramaribo(Zone):
        name = 'Paramaribo'
        observances = [
            Observance(gmtoff=(-3, -40, -40),
                       rules=None,
                       format='LMT',
                       until=1911),
            Observance(gmtoff=(-3, -40, -52),
                       rules=None,
                       format='PMT',
                       until=1935),
            Observance(gmtoff=(-3, -40, -36),
                       rules=None,
                       format='PMT',
                       until=(1945, Oct)),
            Observance(gmtoff=(-3, -30),
                       rules=None,
                       format='NEGT',
                       until=(1975, Nov, 20)),
            Observance(gmtoff=(-3, -30),
                       rules=None,
                       format='SRT',
                       until=(1984, Oct)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='SRT',
                       until=None),
        ]

    class Port_of_Spain(Zone):
        name = 'Port_of_Spain'
        observances = [
            Observance(gmtoff=(-4, -6, -4),
                       rules=None,
                       format='LMT',
                       until=(1912, Mar, 2)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AST',
                       until=None),
        ]

    class Porto_Velho(Zone):
        name = 'Porto_Velho'
        observances = [
            Observance(gmtoff=(-4, -15, -36),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=(1988, Sep, 12)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=None),
        ]

    class Recife(Zone):
        name = 'Recife'
        observances = [
            Observance(gmtoff=(-2, -19, -36),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(1990, Sep, 17)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(1999, Sep, 30)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2000, Oct, 15)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=(2001, Sep, 13)),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(2002, Oct, 1)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=None),
        ]

    class Rio_Branco(Zone):
        name = 'Rio_Branco'
        observances = [
            Observance(gmtoff=(-4, -31, -12),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-5,
                       rules=Brazil,
                       format='AC%sT',
                       until=(1988, Sep, 12)),
            Observance(gmtoff=-5,
                       rules=None,
                       format='ACT',
                       until=(2008, Jun, 24, 0, 0, wall)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=(2013, Nov, 10)),
            Observance(gmtoff=-5,
                       rules=None,
                       format='ACT',
                       until=None),
        ]

    class Santarem(Zone):
        name = 'Santarem'
        observances = [
            Observance(gmtoff=(-3, -38, -48),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-4,
                       rules=Brazil,
                       format='AM%sT',
                       until=(1988, Sep, 12)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='AMT',
                       until=(2008, Jun, 24, 0, 0, wall)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='BRT',
                       until=None),
        ]

    class Santiago(Zone):
        name = 'Santiago'
        observances = [
            Observance(gmtoff=(-4, -42, -46),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=(-4, -42, -46),
                       rules=None,
                       format='SMT',
                       until=(1910, Jan, 10)),
            Observance(gmtoff=-5,
                       rules=None,
                       format='CLT',
                       until=(1916, Jul, 1)),
            Observance(gmtoff=(-4, -42, -46),
                       rules=None,
                       format='SMT',
                       until=(1918, Sep, 10)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='CLT',
                       until=(1919, Jul, 1)),
            Observance(gmtoff=(-4, -42, -46),
                       rules=None,
                       format='SMT',
                       until=(1927, Sep, 1)),
            Observance(gmtoff=-5,
                       rules=Chile,
                       format='CL%sT',
                       until=(1932, Sep, 1)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='CLT',
                       until=(1942, Jun, 1)),
            Observance(gmtoff=-5,
                       rules=None,
                       format='CLT',
                       until=(1942, Aug, 1)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='CLT',
                       until=(1946, Jul, 15)),
            Observance(gmtoff=-4,
                       rules='1:00',
                       format='CLST',
                       until=(1946, Sep, 1)),
            Observance(gmtoff=-4,
                       rules=None,
                       format='CLT',
                       until=(1947, Apr, 1)),
            Observance(gmtoff=-5,
                       rules=None,
                       format='CLT',
                       until=(1947, May, 21, 23, 0, wall)),
            Observance(gmtoff=-4,
                       rules=Chile,
                       format='CL%sT',
                       until=None),
        ]

    class Sao_Paulo(Zone):
        name = 'Sao_Paulo'
        observances = [
            Observance(gmtoff=(-3, -6, -28),
                       rules=None,
                       format='LMT',
                       until=1914),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=(1963, Oct, 23, 0, 0, wall)),
            Observance(gmtoff=-3,
                       rules='1:00',
                       format='BRST',
                       until=1964),
            Observance(gmtoff=-3,
                       rules=Brazil,
                       format='BR%sT',
                       until=None),
        ]

class Antarctica:
    class Palmer(Zone):
        name = 'Palmer'
        observances = [
            Observance(gmtoff=0,
                       rules=None,
                       format='-00',
                       until=1965),
            Observance(gmtoff=-4,
                       rules=Arg,
                       format='AR%sT',
                       until=(1969, Oct, 5)),
            Observance(gmtoff=-3,
                       rules=Arg,
                       format='AR%sT',
                       until=(1982, May)),
            Observance(gmtoff=-4,
                       rules=Chile,
                       format='CL%sT',
                       until=None),
        ]

class Atlantic:
    class South_Georgia(Zone):
        name = 'South_Georgia'
        observances = [
            Observance(gmtoff=(-2, -26, -8),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=-2,
                       rules=None,
                       format='GST',
                       until=None),
        ]

    class Stanley(Zone):
        name = 'Stanley'
        observances = [
            Observance(gmtoff=(-3, -51, -24),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=(-3, -51, -24),
                       rules=None,
                       format='SMT',
                       until=(1912, Mar, 12)),
            Observance(gmtoff=-4,
                       rules=Falk,
                       format='FK%sT',
                       until=(1983, May)),
            Observance(gmtoff=-3,
                       rules=Falk,
                       format='FK%sT',
                       until=(1985, Sep, 15)),
            Observance(gmtoff=-4,
                       rules=Falk,
                       format='FK%sT',
                       until=(2010, Sep, 5, 2, 0, wall)),
            Observance(gmtoff=-3,
                       rules=None,
                       format='FKST',
                       until=None),
        ]

class Pacific:
    class Easter(Zone):
        name = 'Easter'
        observances = [
            Observance(gmtoff=(-7, -17, -28),
                       rules=None,
                       format='LMT',
                       until=1890),
            Observance(gmtoff=(-7, -17, -28),
                       rules=None,
                       format='EMT',
                       until=(1932, Sep)),
            Observance(gmtoff=-7,
                       rules=Chile,
                       format='EAS%sT',
                       until=(1982, Mar, 14, 3, 0, utc)),
            Observance(gmtoff=-6,
                       rules=Chile,
                       format='EAS%sT',
                       until=None),
        ]

    class Galapagos(Zone):
        name = 'Galapagos'
        observances = [
            Observance(gmtoff=(-5, -58, -24),
                       rules=None,
                       format='LMT',
                       until=1931),
            Observance(gmtoff=-5,
                       rules=None,
                       format='ECT',
                       until=1986),
            Observance(gmtoff=-6,
                       rules=None,
                       format='GALT',
                       until=None),
        ]

